/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ServiceManagementService } from "../serviceManagement.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ServiceManagementCreateInput } from "./ServiceManagementCreateInput";
import { ServiceManagement } from "./ServiceManagement";
import { ServiceManagementFindManyArgs } from "./ServiceManagementFindManyArgs";
import { ServiceManagementWhereUniqueInput } from "./ServiceManagementWhereUniqueInput";
import { ServiceManagementUpdateInput } from "./ServiceManagementUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ServiceManagementControllerBase {
  constructor(
    protected readonly service: ServiceManagementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ServiceManagement })
  @nestAccessControl.UseRoles({
    resource: "ServiceManagement",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createServiceManagement(
    @common.Body() data: ServiceManagementCreateInput
  ): Promise<ServiceManagement> {
    return await this.service.createServiceManagement({
      data: data,
      select: {
        createdAt: true,
        id: true,
        service: true,
        updatedAt: true,
        updates: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ServiceManagement] })
  @ApiNestedQuery(ServiceManagementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ServiceManagement",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceManagements(
    @common.Req() request: Request
  ): Promise<ServiceManagement[]> {
    const args = plainToClass(ServiceManagementFindManyArgs, request.query);
    return this.service.serviceManagements({
      ...args,
      select: {
        createdAt: true,
        id: true,
        service: true,
        updatedAt: true,
        updates: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ServiceManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceManagement",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceManagement(
    @common.Param() params: ServiceManagementWhereUniqueInput
  ): Promise<ServiceManagement | null> {
    const result = await this.service.serviceManagement({
      where: params,
      select: {
        createdAt: true,
        id: true,
        service: true,
        updatedAt: true,
        updates: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ServiceManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceManagement",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateServiceManagement(
    @common.Param() params: ServiceManagementWhereUniqueInput,
    @common.Body() data: ServiceManagementUpdateInput
  ): Promise<ServiceManagement | null> {
    try {
      return await this.service.updateServiceManagement({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          service: true,
          updatedAt: true,
          updates: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ServiceManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceManagement",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteServiceManagement(
    @common.Param() params: ServiceManagementWhereUniqueInput
  ): Promise<ServiceManagement | null> {
    try {
      return await this.service.deleteServiceManagement({
        where: params,
        select: {
          createdAt: true,
          id: true,
          service: true,
          updatedAt: true,
          updates: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
